GROUP MEMBER :1. ANUJ MEENA (202001038) 2. ANKIT RATHWA (202001190) 3. HEMISH SALAVIYA (202001206) 4. HARSH PARMAR (202001072) 5. CHANDRAPRAKASH CHAUDHARY (202001009)

CONTRIBUTION::  ANUJ MEENA (35) HEMISH SALAVIYA(25) CHANDRAPRAKASH CHAUDHARAY(20) ANKIT RATHWA (20)  HARSH PARMAR (0)

The 2023 ICC Men's Cricket World Cup is the 13th edition of the Cricket World Cup, a quadrennial One Day International (ODI) cricket tournament contested by men's national teams and organized by the International Cricket Council (ICC). The tournament is being hosted by India, it started on 5 October and is scheduled to conclude on 19 November 2023. England are the defending champions, having won the 2019 edition.

In [ ]:
# importing python libarary
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import pandas as pd
df1 = pd.read_csv('/content/deliveries.csv')
df1

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,0,NaN,NaN,NaN,NaN,NaN,caught,GD Phillips,NaN,NaN

In [ ]:
df2 = pd.read_csv('/content/matches.csv')
df3 = pd.read_csv('/content/points_table.csv')

In [ ]:
df1.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [ ]:
df2.columns

Index(['season', 'team1', 'team2', 'date', 'match_number', 'venue', 'city',
       'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'winner_runs',
       'winner_wickets', 'match_type'],
      dtype='object')

In [ ]:
df3.columns

Index(['Ranking', 'Team', 'Matches', 'Won', 'Lost', 'Tie', 'No Results',
       'Points', 'Net Run Rate', 'Series Form', 'Next Match', 'For',
       'Against'],
      dtype='object')

In [ ]:
#same name columns in df1 and matches
list(set((df1.columns).intersection(df2.columns)))

['match_id', 'venue', 'season']

In [ ]:
#renaming columns in matches
df2.rename(columns={"match_number":"match_id", "start_date":"date"}, inplace=True)

In [ ]:
df1.isna().sum()

match_id                      0
season                        0
start_date                    0
venue                         0
innings                       0
ball                          0
batting_team                  0
bowling_team                  0
striker                       0
non_striker                   0
bowler                        0
runs_off_bat                  0
extras                        0
wides                     16949
noballs                   17338
byes                      17354
legbyes                   17263
penalty                   17379
wicket_type               16889
player_dismissed          16889
other_wicket_type         17380
other_player_dismissed    17380
dtype: int64

In [ ]:
#creating a wicket column to get boolean of wicket fall
df1["wicket"] = df1["player_dismissed"].apply(lambda x: 1 if isinstance(x, str) else 0)
df1

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,wicket
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,NaN,NaN,caught,GD Phillips,NaN,NaN,1

In [ ]:
#filling na values
df1[["wides", "noballs", "byes", "legbyes", "penalty"]] = df1[["wides", "noballs", "byes", "legbyes", "penalty"]].fillna(0)

In [ ]:
df1.wicket_type.fillna("no wicket", inplace=True)
df1.player_dismissed.fillna("no wicket", inplace=True)

In [ ]:
df1.isna().sum()

match_id                      0
season                        0
start_date                    0
venue                         0
innings                       0
ball                          0
batting_team                  0
bowling_team                  0
striker                       0
non_striker                   0
bowler                        0
runs_off_bat                  0
extras                        0
wides                         0
noballs                       0
byes                          0
legbyes                       0
penalty                       0
wicket_type               16889
player_dismissed          16889
other_wicket_type         17380
other_player_dismissed    17380
wicket                        0
dtype: int64

In [ ]:
df2.isna().sum()

season              0
team1               0
team2               0
date                0
match_id            0
venue               0
city                0
toss_winner         0
toss_decision       0
player_of_match     0
umpire1             0
umpire2             0
reserve_umpire      1
match_referee       0
winner              0
winner_runs        16
winner_wickets     16
match_type          0
dtype: int64

In [ ]:
df2.rename(columns={"winner_runs":"win_by_runs", "winner_wickets":"win_by_wickets"}, inplace=True)
df2.win_by_runs.fillna(0, inplace=True)
df2.win_by_wickets.fillna(0, inplace=True)
df2.reserve_umpire.fillna("unknown", inplace=True)

In [ ]:
df2.isna().sum()

season             0
team1              0
team2              0
date               0
match_id           0
venue              0
city               0
toss_winner        0
toss_decision      0
player_of_match    0
umpire1            0
umpire2            0
reserve_umpire     0
match_referee      0
winner             0
win_by_runs        0
win_by_wickets     0
match_type         0
dtype: int64

In [ ]:
#creating over and balls from ball column which is in 0.1, 0.2 format for first over
df1["ball"] = df1["ball"].astype(str)
df1[["over", "ball_num"]] = df1["ball"].str.split(".", expand=True).astype(int)
df1["ball"] = df1["ball"].astype(float)
df1["over"] = df1["over"] + 1
df1["ball_left"] = 306 - (df1["over"]*6 + df1["ball_num"])

In [ ]:
#creating total runs column to calculate runs on each ball incusive of extras
df1["total_runs"] = df1["runs_off_bat"] + df1["extras"]

In [ ]:
#creating innings df so we can merger total runs for each innings with in original df
innings = df1.groupby(["match_id", "innings"])["total_runs"].sum().reset_index()
innings.rename(columns={"total_runs":"innings_total"}, inplace=True)

In [ ]:
deliveries = df1.merge(innings, on=["match_id", "innings"])
deliveries

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,wicket,over,ball_num,ball_left,total_runs,innings_total
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,0,1,1,299,0,282
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,0,1,2,298,6,282
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,0,1,3,297,1,282
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,NaN,NaN,NaN,NaN,0,1,4,296,1,282
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,NaN,0,1,5,295,4,282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,NaN,0,35,5,91,0,167
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,NaN,0,35,6,90,0,167
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,NaN,0,36,1,89,0,167
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,NaN,0,36,2,88,6,167
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,caught,GD Phillips,NaN,NaN,1,36,3,87,0,167

In [ ]:
#calculating cumulative runs
deliveries["cumulative_runs"] = deliveries.groupby(["match_id", "innings"])["total_runs"].cumsum()
deliveries

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,player_dismissed,other_wicket_type,other_player_dismissed,wicket,over,ball_num,ball_left,total_runs,innings_total,cumulative_runs
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,0,1,1,299,0,282,0
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,0,1,2,298,6,282,6
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,0,1,3,297,1,282,7
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,NaN,NaN,NaN,0,1,4,296,1,282,8
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,NaN,0,1,5,295,4,282,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,0,35,5,91,0,167,161
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,NaN,0,35,6,90,0,167,161
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,0,36,1,89,0,167,161
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,NaN,0,36,2,88,6,167,167
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,GD Phillips,NaN,NaN,1,36,3,87,0,167,167

In [ ]:
#creating run rate column
deliveries["run_rate"] = deliveries.groupby(["match_id","innings"]).apply(lambda x: (x["cumulative_runs"]*6)/(300-x["ball_left"])).reset_index(level=[0,1], drop=True)
deliveries

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,other_wicket_type,other_player_dismissed,wicket,over,ball_num,ball_left,total_runs,innings_total,cumulative_runs,run_rate
0,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.1,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,0,1,1,299,0,282,0,0.000000
1,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.2,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,0,1,2,298,6,282,6,18.000000
2,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.3,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,0,1,3,297,1,282,7,14.000000
3,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.4,England,New Zealand,DJ Malan,JM Bairstow,...,NaN,NaN,0,1,4,296,1,282,8,12.000000
4,1,2023/24,2023-10-05,"Narendra Modi Stadium, Ahmedabad",1,0.5,England,New Zealand,JM Bairstow,DJ Malan,...,NaN,NaN,0,1,5,295,4,282,12,14.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17375,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.5,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,0,35,5,91,0,167,161,4.622010
17376,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,34.6,New Zealand,South Africa,MJ Henry,GD Phillips,...,NaN,NaN,0,35,6,90,0,167,161,4.600000
17377,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.1,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,0,36,1,89,0,167,161,4.578199
17378,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.2,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,0,36,2,88,6,167,167,4.726415
17379,32,2023/24,2023-11-01,"Maharashtra Cricket Association Stadium, Pune",2,35.3,New Zealand,South Africa,GD Phillips,MJ Henry,...,NaN,NaN,1,36,3,87,0,167,167,4.704225

In [ ]:
#filtering for innings1 and 2 so we can add some columns respectively
innings_1 = deliveries[deliveries["innings"] == 1]

innings_1 = innings_1.groupby("match_id")["cumulative_runs"].max().reset_index()
innings_1.rename(columns={"cumulative_runs": "target"}, inplace=True)

innings_2 = deliveries[deliveries["innings"] == 2]
innings_2 = innings_2.merge(innings_1, on="match_id", how="left")
innings_2["target"] = innings_2["target"]+1

In [ ]:
#adding runs needed and rrr to innings 2
innings_2["runs_needed"] = innings_2["target"] - innings_2["cumulative_runs"]
innings_2["required_run_rate"] = (innings_2["runs_needed"]*6) / innings_2["ball_left"]

In [ ]:
#adding wickets remaining to innings 2
innings_2["wickets_remaining"] = innings_2.groupby("match_id")["wicket"].apply(lambda x: 10 - x.cumsum()).reset_index(level=0, drop=True)
#innings 1 data
innings_1_f = deliveries[deliveries["innings"] == 1]
#adding wickets remaining
innings_1_f["wickets_remaining"] = innings_1_f.groupby("match_id")["wicket"].apply(lambda x: 10 - x.cumsum()).reset_index(level=0, drop=True)

<ipython-input-25-14bc515928e5>:2: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  innings_2["wickets_remaining"] = innings_2.groupby("match_id")["wicket"].apply(lambda x: 10 - x.cumsum()).reset_index(level=0, drop=True)
<ipython-input-25-14bc515928e5>:6: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  innings_1_f["wickets_remaining"] = innings_1_f.groupby("match_id")["wicket"].apply(lambda x: 10 - x.cumsum()).reset_index(level=0, drop=True)
<ipython-input-25-14bc515928e5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  innings_1_f["wickets_remaining"] = innings_1_f.groupby("match_id")["wicket"].apply(lambda x: 10 - x.cumsum()).reset_index(level=0, drop=True)

In [ ]:
#concatinating innings1,2
innings = pd.concat([innings_1_f,innings_2])
innings.isna().sum()

match_id                      0
season                        0
start_date                    0
venue                         0
innings                       0
ball                          0
batting_team                  0
bowling_team                  0
striker                       0
non_striker                   0
bowler                        0
runs_off_bat                  0
extras                        0
wides                         0
noballs                       0
byes                          0
legbyes                       0
penalty                       0
wicket_type               16889
player_dismissed          16889
other_wicket_type         17380
other_player_dismissed    17380
wicket                        0
over                          0
ball_num                      0
ball_left                     0
total_runs                    0
innings_total                 0
cumulative_runs               0
run_rate                      0
wickets_remaining          4243
target                     9493
runs_needed                9493
required_run_rate          9493
dtype: int64

In [ ]:
len(innings)

17380

In [ ]:
innings.fillna(0, inplace=True)
innings = innings[~((innings.required_run_rate > 500) | (innings.run_rate > 100))]


#merging with matches data to get winners and other data that can help our model
innings = innings.merge(df2[["match_id","winner", "win_by_runs", "win_by_wickets"]], on="match_id")

In [ ]:
df2.columns

Index(['season', 'team1', 'team2', 'date', 'match_id', 'venue', 'city',
       'toss_winner', 'toss_decision', 'player_of_match', 'umpire1', 'umpire2',
       'reserve_umpire', 'match_referee', 'winner', 'win_by_runs',
       'win_by_wickets', 'match_type'],
      dtype='object')

In [ ]:
#adding result column
innings["result"] = innings.apply(lambda x: 1 if x["batting_team"] == x["winner"] else 0, axis=1)
#making the data random to avoid overfitting
innings = innings.sample(frac=1)

In [ ]:
#defining model data for prediction
model_column = innings[["venue", "batting_team", "bowling_team", "ball", "innings_total", "wickets_remaining", "run_rate", "required_run_rate",
                      "ball_left", "runs_needed", "win_by_runs", "win_by_wickets", "target", "result"]]

In [ ]:
model_column.isna().sum()

venue                0
batting_team         0
bowling_team         0
ball                 0
innings_total        0
wickets_remaining    0
run_rate             0
required_run_rate    0
ball_left            0
runs_needed          0
win_by_runs          0
win_by_wickets       0
target               0
result               0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [ ]:
model_column.dtypes

venue                 object
batting_team          object
bowling_team          object
ball                 float64
innings_total          int64
wickets_remaining    float64
run_rate             float64
required_run_rate    float64
ball_left              int64
runs_needed          float64
win_by_runs          float64
win_by_wickets       float64
target               float64
result                 int64
dtype: object

In [ ]:
#differentiating data from result column
X = model_column.iloc[:,:-1]
y = model_column.iloc[:, -1]

In [ ]:
#splitting data to fit into model
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [ ]:
#defining columns to encode and scale
ohe_cols = [col for col in X.columns if X[col].dtypes not in (int, float)]
scale_cols = [col for col in X.columns if X[col].dtypes in (int, float)]
ohe_cols, scale_cols

(['venue', 'batting_team', 'bowling_team'],
 ['ball',
  'innings_total',
  'wickets_remaining',
  'run_rate',
  'required_run_rate',
  'ball_left',
  'runs_needed',
  'win_by_runs',
  'win_by_wickets',
  'target'])

In [ ]:
#column transformer
ct = make_column_transformer(
    (OneHotEncoder(sparse=False, drop="first"), ohe_cols),
    remainder="passthrough"
)

In [ ]:
#defining pipeline and steps
pipe = make_pipeline(
    ct,
    LogisticRegression(solver="liblinear")
)

In [ ]:
#fitting into model
pipe.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['venue', 'batting_team',
                                                   'bowling_team'])])),
                ('logisticregression', LogisticRegression(solver='liblinear'))])

In [ ]:
#testing the model and its accuracy
pred = pipe.predict(x_test)
acc = accuracy_score(y_test, pred)
acc

0.9568469505178366

In [ ]:
pipe.predict_proba(x_test)[9]

array([0.03832177, 0.96167823])

In [46]:
from sklearn.metrics import precision_score, recall_score, f1_score

# After fitting the model, calculate additional metrics
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)



#Precision: 0.959711136450019
#Recall: 0.9549924357034796
#F1 Score: 0.9573459715639812

Precision: 0.959711136450019
Recall: 0.9549924357034796
F1 Score: 0.9573459715639812